// Builds the two files node-proc-worker.js needs in a browser:
//   poc-bundle.js  -- vfs/bindings/boot/kernel-vfs behind a tiny CommonJS shim
//   node-lib.json  -- node's lib/*.js as { id: source }
// The .js files stay plain CommonJS so `node run.js ./lib` keeps working unchanged.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { join, relative } from 'node:path';

const here = new URL('.', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const LIB = process.argv[2] || join(here, 'lib');

// ---- poc-bundle.js -----------------------------------------------------------
const MODULES = ['vfs.js', 'buffer-binding.js', 'tcp-wrap.js', 'dns-wrap.js', 'http-parser.js', 'bindings.js', 'boot.js', 'syscall-bridge.js', 'kernel-vfs.js', 'repl.js', 'shim-crypto.js', 'shim-zlib.js', 'shim-http.js', 'shims.js', 'node-main.js'];
const parts = [];
parts.push(`// GENERATED by build.mjs -- do not edit. Sources: ${MODULES.join(' ')}
(function () {
  'use strict';
  const __defs = {}, __cache = {};
  function require(id) {
    const key = String(id).replace(/^\\.\\//, '').replace(/\\.js$/, '').replace(/\\.json$/, '');
    if (key in __cache) return __cache[key];
    const def = __defs[key];
    if (!def) throw new Error('bundle: no module ' + id);
    const module = { exports: {} };
    __cache[key] = module.exports;
    def(module, module.exports, require);
    __cache[key] = module.exports;
    return __cache[key];
  }
  self.__pocRequire = require;
`);
parts.push(`  __defs['constants'] = function (module) { module.exports = ${readFileSync(join(here, 'constants.json'), 'utf8')}; };\n`);
for (const f of MODULES) {
  const src = readFileSync(join(here, f), 'utf8');
  parts.push(`  __defs[${JSON.stringify(f.replace(/\.js$/, ''))}] = function (module, exports, require) {\n${src}\n};\n`);
}
parts.push('})();\n');
writeFileSync(join(here, 'poc-bundle.js'), parts.join(''));

// ---- node-lib.json -----------------------------------------------------------
let n = 0;
const out = {};
(function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) { walk(p); continue; }
    if (!e.name.endsWith('.js')) continue;
    const id = relative(LIB, p).split(/[\\/]/).join('/').replace(/\.js$/, '');
    out[id] = readFileSync(p, 'utf8');
    n++;
  }
})(LIB);
writeFileSync(join(here, 'node-lib.json'), JSON.stringify(out));
// The .gz is what SHIPS: 3967KB -> 883KB, which matters both in git and on the wire.
// The worker inflates it with DecompressionStream, which we already depend on.
writeFileSync(join(here, 'node-lib.json.gz'), gzipSync(JSON.stringify(out), { level: 9 }));

const kb = (f) => Math.round(statSync(join(here, f)).size / 1024);
console.log('poc-bundle.js :', kb('poc-bundle.js'), 'KB');
console.log('node-lib.json :', kb('node-lib.json'), 'KB  (' + n + ' modules)');
console.log('node-lib.json.gz:', kb('node-lib.json.gz'), 'KB  <- shipped');
